# fly.toml app configuration file generated for still-violet-5984 on 2023-06-05T21:20:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-violet-5984"
primary_region = "cdg"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
